In [222]:
import numpy as np
import cv2

In [223]:
input = (np.random.rand(40, 20) * 10).astype('uint8')

In [224]:
input

array([[6, 4, 1, 0, 3, 3, 2, 0, 8, 5, 8, 7, 0, 0, 7, 0, 2, 9, 3, 1],
       [3, 2, 4, 1, 4, 3, 1, 7, 2, 8, 7, 1, 7, 4, 8, 6, 0, 4, 8, 7],
       [7, 9, 4, 4, 5, 7, 4, 5, 1, 2, 3, 5, 4, 0, 8, 2, 4, 7, 5, 3],
       [4, 4, 5, 2, 3, 7, 9, 0, 0, 2, 0, 7, 0, 2, 6, 2, 3, 1, 4, 5],
       [4, 9, 0, 9, 7, 8, 3, 3, 6, 4, 0, 5, 5, 3, 2, 6, 6, 5, 9, 9],
       [6, 2, 1, 1, 2, 4, 7, 9, 3, 2, 0, 8, 5, 9, 2, 9, 8, 6, 6, 9],
       [7, 9, 7, 5, 3, 4, 8, 9, 9, 1, 9, 0, 5, 4, 2, 0, 4, 9, 3, 7],
       [1, 6, 8, 0, 2, 4, 2, 1, 2, 0, 7, 2, 6, 8, 5, 2, 2, 9, 5, 7],
       [4, 4, 4, 3, 6, 2, 7, 0, 8, 1, 3, 3, 1, 0, 2, 5, 8, 8, 9, 3],
       [6, 0, 8, 3, 4, 0, 0, 2, 1, 9, 2, 6, 0, 7, 6, 7, 9, 8, 3, 5],
       [4, 2, 1, 3, 1, 2, 6, 2, 8, 8, 3, 9, 4, 0, 7, 4, 5, 0, 9, 9],
       [4, 4, 0, 3, 7, 1, 6, 1, 2, 8, 3, 5, 2, 9, 1, 9, 0, 5, 4, 7],
       [4, 3, 6, 5, 3, 5, 0, 2, 4, 1, 3, 9, 1, 4, 4, 3, 9, 7, 4, 4],
       [0, 8, 6, 0, 9, 0, 4, 4, 6, 9, 3, 1, 5, 8, 8, 9, 4, 8, 4, 6],
       [1, 7, 3, 5, 7, 9, 7, 2, 0,

In [225]:
mask = np.zeros((40, 20)).astype('uint8')
m = np.ones((8, 16))*3
m2 = np.ones((25, 8))*3
mask[3:11, 3:19] = m
mask[10:35, 8:16] = m2

In [226]:
mask

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3,

In [227]:
mask[12:12+5, 6:6+8]

array([[0, 0, 3, 3, 3, 3, 3, 3],
       [0, 0, 3, 3, 3, 3, 3, 3],
       [0, 0, 3, 3, 3, 3, 3, 3],
       [0, 0, 3, 3, 3, 3, 3, 3],
       [0, 0, 3, 3, 3, 3, 3, 3]], dtype=uint8)

In [228]:
idx, col = np.where(mask!=0)

In [229]:
idx

array([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11,
       12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 14,
       14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16,
       16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18,
       18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20,
       20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22,
       22, 22, 22, 23, 23

In [230]:
col

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18,  8,  9, 10, 11, 12, 13, 14, 15,
        8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15,  8,
        9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15,  8,  9,
       10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10,
       11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11,
       12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12,
       13, 14, 15,  8,  9

In [231]:
def detect_large_mask(input, mask, idx, col):
    thresh = 2
    count = 1
    seq_h, seq_w = [], []
    rec = []
    idx_set = list(set(idx))
    for i in idx_set:
        if np.sum(idx == i) >= thresh:
            seq_h.append([i, np.sum(idx == i)])

    if seq_h != []:
        seq_h = np.array(seq_h)
        seq_h_set = np.array(list(set(seq_h[:, 1])))

        seq_h_div = []
        for i in seq_h_set:
            seq_h_div.append(seq_h[seq_h[:, 1] == i])

        seq_h_div = np.array(seq_h_div)
        for i in seq_h_div:
            s_h, e_h = i[0, 0], i[-1, 0]
            tmp_rec = np.arange(s_h, e_h+1)
            if len(tmp_rec) >= thresh:
                if np.all(i[:, 0] == tmp_rec):
                    tmp_idx, tmp_col = np.where([idx==s_h])
                    s_v = col[tmp_col.min()]
                    rec.append(np.array([s_h, s_v, len(tmp_rec), i[0, 1]]))

    return np.array(rec)

In [232]:
rec = detect_large_mask(input, mask, idx, col)

In [233]:
rec

array([[ 3,  3,  8, 16],
       [11,  8, 24,  8]])

In [234]:
input

array([[6, 4, 1, 0, 3, 3, 2, 0, 8, 5, 8, 7, 0, 0, 7, 0, 2, 9, 3, 1],
       [3, 2, 4, 1, 4, 3, 1, 7, 2, 8, 7, 1, 7, 4, 8, 6, 0, 4, 8, 7],
       [7, 9, 4, 4, 5, 7, 4, 5, 1, 2, 3, 5, 4, 0, 8, 2, 4, 7, 5, 3],
       [4, 4, 5, 2, 3, 7, 9, 0, 0, 2, 0, 7, 0, 2, 6, 2, 3, 1, 4, 5],
       [4, 9, 0, 9, 7, 8, 3, 3, 6, 4, 0, 5, 5, 3, 2, 6, 6, 5, 9, 9],
       [6, 2, 1, 1, 2, 4, 7, 9, 3, 2, 0, 8, 5, 9, 2, 9, 8, 6, 6, 9],
       [7, 9, 7, 5, 3, 4, 8, 9, 9, 1, 9, 0, 5, 4, 2, 0, 4, 9, 3, 7],
       [1, 6, 8, 0, 2, 4, 2, 1, 2, 0, 7, 2, 6, 8, 5, 2, 2, 9, 5, 7],
       [4, 4, 4, 3, 6, 2, 7, 0, 8, 1, 3, 3, 1, 0, 2, 5, 8, 8, 9, 3],
       [6, 0, 8, 3, 4, 0, 0, 2, 1, 9, 2, 6, 0, 7, 6, 7, 9, 8, 3, 5],
       [4, 2, 1, 3, 1, 2, 6, 2, 8, 8, 3, 9, 4, 0, 7, 4, 5, 0, 9, 9],
       [4, 4, 0, 3, 7, 1, 6, 1, 2, 8, 3, 5, 2, 9, 1, 9, 0, 5, 4, 7],
       [4, 3, 6, 5, 3, 5, 0, 2, 4, 1, 3, 9, 1, 4, 4, 3, 9, 7, 4, 4],
       [0, 8, 6, 0, 9, 0, 4, 4, 6, 9, 3, 1, 5, 8, 8, 9, 4, 8, 4, 6],
       [1, 7, 3, 5, 7, 9, 7, 2, 0,

In [235]:
def check_rec_position(mask, out1, out2, grid, length, valid):
    if np.sum(mask[out1[0]:out1[2], out1[1]:out1[3]] > 0) > grid * length / 8:
        out1 = out2
    if np.sum(mask[out2[0]:out2[2], out2[1]:out2[3]] > 0) > grid * length / 8:
        if np.all(out1 == out2):
            valid = False
        else:
            out2 = out1
    
    return out1, out2, valid

In [236]:
def arange_rec_out(rec_out, opp_rec, grid):
    if rec_out.shape[1] >= grid / 8 and rec_out.shape[1] < grid:
        rec_out = cv2.resize(rec_out, (grid, rec_out.shape[0]))
    elif rec_out.shape[1] < grid / 8:
        rec_out = opp_rec
        
    return rec_out

In [237]:
def pre_grid_support(input, mask, rec):
    if rec != []:
        print(rec)
        for r in rec:
            valid_lr, valid_ud = True, True
            y, x, h, w = r
            g_h = int(h / 8)
            g_w = int(w / 8)
            print('g_h: {}, g_w: {}'.format(g_h, g_w))
#             print(x, g_w)
#             print(x-g_w, x)
#             print(x+w, x+w+g_w)

            out_l = [y, x-g_w, y+h, x]
            out_r = [y, x+w, y+h, x+w+g_w]
            out_u = [y-g_h, x, y, x+w]
            out_d = [y+h, x, y+h+g_h, x+w]
            
            out_l, out_r, valid_lr = check_rec_position(mask, out_l, out_r, g_w, h, valid_lr)
            out_u, out_d, valid_ud = check_rec_position(mask, out_u, out_d, g_h, w, valid_ud)
            
            if valid_lr:
                rec_out_l = input[out_l[0]:out_l[2], out_l[1]:out_l[3]]
                rec_out_r = input[out_r[0]:out_r[2], out_r[1]:out_r[3]]
                rec_out_l = arange_rec_out(rec_out_l, rec_out_r, g_w)
                rec_out_r = arange_rec_out(rec_out_r, rec_out_l, g_w)
#                 print('rec_out_l', rec_out_l)
#                 print('rec_out_r', rec_out_r)

                input[y : y+h, x+2*g_w : x+3*g_w] = (2 * rec_out_l + 1 * rec_out_r) / 3
                input[y : y+h, x+w-3*g_w : x+w-2*g_w] = (1 * rec_out_l + 2 * rec_out_r) / 3
                mask[y : y+h, x+2*g_w : x+3*g_w] = 0
                mask[y : y+h, x+w-3*g_w : x+w-2*g_w] = 0

            if valid_ud:
                rec_out_u = input[out_u[0]:out_u[2], out_u[1]:out_u[3]]
                rec_out_d = input[out_d[0]:out_d[2], out_d[1]:out_d[3]]
                print('rec_out_u', rec_out_u.shape)
                print('rec_out_d', rec_out_d.shape)
                rec_out_u = arange_rec_out(rec_out_u, rec_out_d, g_h)
                rec_out_d = arange_rec_out(rec_out_d, rec_out_u, g_h)
                print('rec_out_u', rec_out_u.shape)
                print('rec_out_d', rec_out_d.shape)

                input[y+2*g_h : y+3*g_h, x : x+w] = (2 * rec_out_u + 1 * rec_out_d) / 3
                input[y+h-3*g_h : y+h-2*g_h, x : x+w] = (1 * rec_out_u + 2 * rec_out_d) / 3
                mask[y+2*g_h : y+3*g_h, x : x+w] = 0
                mask[y+h-3*g_h : y+h-2*g_h, x : x+w] = 0


    return input, mask

In [238]:
output, n_mask = pre_grid_support(input, mask, rec)

[[ 3  3  8 16]
 [11  8 24  8]]
g_h: 1, g_w: 2
rec_out_u (1, 16)
rec_out_d (1, 16)
rec_out_u (1, 16)
rec_out_d (1, 16)
g_h: 3, g_w: 1
rec_out_u (3, 8)
rec_out_d (3, 8)
rec_out_u (3, 8)
rec_out_d (3, 8)


/Users/tanimu/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise != comparison failed; this will raise an error in the future.
  


In [239]:
mask

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0],
       [0, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 3, 3, 0, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 3, 3, 0, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 3, 3, 0, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3,