In [1]:
import numpy as np

In [104]:
input = np.zeros((20, 15))
mask = np.ones((6, 8))*3
mask2 = np.ones((5, 4))*3
input[11:17, 6:14] = mask
input[7:12, 4:8] = mask2

In [105]:
input

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 0.],
       [0., 0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 3., 3., 3., 0.],
       [0., 0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 3., 3., 3., 0.],
       [0., 0., 0., 0., 0., 0., 3.

In [129]:
input[12:12+5, 6:6+8]

array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.]])

In [106]:
idx, col = np.where(input!=0)

In [107]:
idx

array([ 7,  7,  7,  7,  8,  8,  8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12,
       13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 15,
       15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16])

In [108]:
col

array([ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13,  6,  7,  8,  9, 10, 11, 12, 13,
        6,  7,  8,  9, 10, 11, 12, 13,  6,  7,  8,  9, 10, 11, 12, 13,  6,
        7,  8,  9, 10, 11, 12, 13,  6,  7,  8,  9, 10, 11, 12, 13])

In [128]:
thresh = 2
count = 1
seq_h, seq_w = [], []
rec = []
idx_set = list(set(idx))
for i in idx_set:
    if np.sum(idx == i) >= thresh:
        seq_h.append([i, np.sum(idx == i)])
        
if seq_h != []:
    seq_h = np.array(seq_h)
    seq_h_set = np.array(list(set(seq_h[:, 1])))
    
    seq_h_div = []
    for i in seq_h_set:
        seq_h_div.append(seq_h[seq_h[:, 1] == i])

    seq_h_div = np.array(seq_h_div)
    for i in seq_h_div:
        s_h, e_h = i[0, 0], i[-1, 0]
        tmp_rec = np.arange(s_h, e_h+1)
        if len(tmp_rec) >= thresh:
            if np.all(i[:, 0] == tmp_rec):
                tmp_idx, tmp_col = np.where([idx==s_h])
                s_v = col[tmp_col.min()]
                rec.append(np.array([s_h, s_v, len(tmp_rec), i[0, 1]]))

print(rec)

[array([12,  6,  5,  8]), array([7, 4, 4, 4])]
